language: objective-c
before_install:
  - gem install xcpretty
  - gem install cocoapods -v '0.38.2'
podfile: BoxContentSDK/Podfile
osx_image: xcode8.2.1
#run on iPhone 7 (10.0) [060AAE67-12D1-4C9B-AD75-71A217E26F0E] (Simulator)
script: 
  - xcodebuild test -scheme BoxContentSDKTests -sdk iphonesimulator -destination 'platform=iOS Simulator,id=060AAE67-12D1-4C9B-AD75-71A217E26F0E' -project BoxContentSDK/BoxContentSDK.xcodeproj -configuration Debug  | xcpretty -c && exit ${PIPESTATUS[0]}
