language: objective-c
before_install:
  - gem install xcpretty
  - gem install cocoapods -v '0.38.2'
podfile: BoxContentSDK/Podfile
osx_image: xcode6.4
script: 
  - xcodebuild test -scheme BoxContentSDKTests -sdk iphonesimulator8.4 -workspace BoxContentSDK/BoxContentSDK.xcworkspace -configuration Debug  | xcpretty -c && exit ${PIPESTATUS[0]}
