name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, edited ]
    branches:
      - main

jobs:
  integration-tests:
    runs-on: macos-12
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=15.5,name=iPhone 11']
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_13.4.app
      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup carthage dependencies
        run: ./scripts/bootstrap
      - name: Run Integration Tests
        run: |
          echo "${INTEGRATION_TESTING_CONFIG}" > IntegrationTests/Resources/Configuration.json
          set -o pipefail && xcodebuild -workspace BoxSDK.xcworkspace -scheme BoxSDKIntegrationTests-iOS -destination "${{ matrix.destination }}" -configuration Debug ENABLE_TESTABILITY=YES test
        env:
          INTEGRATION_TESTING_CONFIG: ${{secrets.INTEGRATION_TESTING_CONFIG}}

